-- Jatra PostgreSQL schema for hosted PostgreSQL (Neon/Supabase/Railway/etc.)
-- Run this file in your hosted PostgreSQL SQL editor before deploying the app.

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  student_id VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(190) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS auth_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash CHAR(64) NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_auth_tokens_user_id ON auth_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_auth_tokens_expires_at ON auth_tokens(expires_at);

CREATE TABLE IF NOT EXISTS ride_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  pickup VARCHAR(255) NOT NULL,
  destinations_json JSONB NOT NULL,
  fare NUMERIC(10,2) NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','accepted','cancelled')),
  accepted_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_ride_requests_status ON ride_requests(status);
CREATE INDEX IF NOT EXISTS idx_ride_requests_customer_id ON ride_requests(customer_id);

CREATE TABLE IF NOT EXISTS ride_request_responses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ride_request_id BIGINT NOT NULL REFERENCES ride_requests(id) ON DELETE CASCADE,
  rider_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  action VARCHAR(20) NOT NULL CHECK (action IN ('accept','decline')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_ride_request_responder UNIQUE (ride_request_id, rider_id)
);

CREATE TABLE IF NOT EXISTS schedule_rides (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  origin_role VARCHAR(20) NOT NULL CHECK (origin_role IN ('rider','customer')),
  pickup VARCHAR(255) NOT NULL,
  destinations_json JSONB NOT NULL,
  available_seat INTEGER NULL,
  fare NUMERIC(10,2) NOT NULL DEFAULT 0,
  ride_date DATE NOT NULL,
  pickup_time TIME NOT NULL,
  drop_time TIME NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active','accepted','cancelled','completed')),
  accepted_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_schedule_rides_origin_status ON schedule_rides(origin_role,status);
CREATE INDEX IF NOT EXISTS idx_schedule_rides_owner_id ON schedule_rides(owner_id);

CREATE TABLE IF NOT EXISTS schedule_responses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  schedule_ride_id BIGINT NOT NULL REFERENCES schedule_rides(id) ON DELETE CASCADE,
  responder_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  action VARCHAR(20) NOT NULL CHECK (action IN ('accept','decline')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_schedule_responder UNIQUE (schedule_ride_id, responder_id)
);

CREATE TABLE IF NOT EXISTS request_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  view_role VARCHAR(20) NOT NULL CHECK (view_role IN ('rider','customer')),
  request_type VARCHAR(30) NOT NULL CHECK (request_type IN ('ride_request','schedule_ride')),
  request_id BIGINT NOT NULL,
  title VARCHAR(80) NOT NULL,
  action VARCHAR(30) NOT NULL,
  details_json JSONB NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_request_history_user_role_created ON request_history(user_id,view_role,created_at DESC);
